MAX_EXPTIME_OFFSET = 2592000
MAX_LEN = 2000

CLIENT_ERROR_CHUNK = 'CLIENT_ERROR bad data chunk'
CLIENT_ERROR_COMMAND = 'CLIENT_ERROR bad command line format'
STORED = 'STORED'
NOT_STORED = 'NOT_STORED'
FIN = 'END'
ERROR = 'ERROR'
QUIT = 'Connection closed by foreign host.'