MAX_EXPTIME_OFFSET = 2592000

CLIENT_ERROR_CHUNK = 'CLIENT_ERROR bad data chunk' #+ERROR
CLIENT_ERROR_COMMAND = 'CLIENT_ERROR bad command line format'
STORED = 'STORED'
NOT_STORED = 'NOT_STORED'
FIN = 'END'
ERROR = 'ERROR'
QUIT = 'Connection closed by foreign host.'
EXISTS = 'EXISTS'
NOT_FOUND = 'NOT_FOUND'

CAS_STORED = 1
CAS_EXISTS = 2
CAS_NOT_FOUND = 3

COMMAND = 0
KEY = 1
SIZE = 4
NOREPLY = 5
CAS_KEY = 5
CAS_NOREPLY = 6

